KongreForm/Models/Basvuru.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KongreForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basvuru
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Basvuru()
        {
            this.BasvuruDetays = new HashSet<BasvuruDetay>();
            this.BasvuruEvraks = new HashSet<BasvuruEvrak>();
        }
    
        public int Id { get; set; }
        public int FKKisiId { get; set; }
        public int FKKongreId { get; set; }
        public Nullable<bool> Onay { get; set; }
        public Nullable<System.DateTime> OnayZaman { get; set; }
        public System.DateTime BasvuruZaman { get; set; }
        public string BasvuruKodu { get; set; }
        public Nullable<int> SunumTipi { get; set; }
        public Nullable<bool> SunucuMu { get; set; }
        public string Ozet { get; set; }
        public Nullable<bool> PosterMi { get; set; }
        public string Baslik { get; set; }
    
        public virtual Kisi Kisi { get; set; }
        public virtual Kongre Kongre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasvuruDetay> BasvuruDetays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasvuruEvrak> BasvuruEvraks { get; set; }
    }
}

KongreForm/Models/BasvuruViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace KongreForm.Models
{
    public partial class OturumVM
    {
        public int Id { get; set; }
      
        public int FKKongreId { get; set; }
        public string OturumAd { get; set; }
        public System.DateTime OturumBaslangic { get; set; }
        public System.DateTime OturumBitis { get; set; }
      
        [Required(ErrorMessage ="Oturum seçin")]
        public bool IsChecked { get; set; }


    }
    public partial class BasvuruDetayVM
    {
        public int Id { get; set; }

        public string OturumAd { get; set; }

        public int FKOturumId { get; set; }

        public string KullaniciAd { get; set; }

        public string KullaniciSoyad { get; set; }
        public Nullable<int> FKKullaniciId { get; set; }
        public int FKBasvuruId { get; set; }
        public Nullable<System.DateTime> OnayZaman { get; set; }
        public Nullable<bool> Onay { get; set; }


    }
    public class BasvuruViewModel
    {

       
        public bool? SunucuMu { get; set; }


        [Required(ErrorMessage = "Ad alanı gereklidir.")]
        [StringLength(30)]
        public string Ad { get; set; }

        [Required(ErrorMessage = "Soyad alanı gereklidir.")]
        [StringLength(50)]
        public string Soyad { get; set; }


        [Required]
        [StringLength(50)]
        [EmailAddress(ErrorMessage = "Lütfen geçerli bir email adresi girin.")]
        public string Email { get; set; }

        [RegularExpression(@"^[1-9]{1}[0-9]{9}[02468]{1}$", ErrorMessage ="Lütfen geçerli bir kimlik numarası adresi girin.")]
        [StringLength(11,MinimumLength =11, ErrorMessage =" Tc kimlik numarası 11 haneli olmalıdır.")]
        public string TcNo { get; set; }

        [StringLength(50,ErrorMessage = "Karakter asimi yaptiniz")]
        public string Kurum { get; set; }


        [StringLength(50, ErrorMessage = "Karakter asimi yaptiniz")]

        public string Meslek { get; set; }


        public int? Egitim { get; set; }

        [Required]
        [Phone(ErrorMessage = "Lütfen telefon numaranızı giriniz")]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage ="Lütfen geçerli bir telefon numarası girin. (5xxxxxxxxx)")]
        public string Telefon { get; set; }

        [Required(ErrorMessage = "Üniversite alanı gereklidir.")]
        [StringLength(50, ErrorMessage = "Karakter asimi yaptiniz")]

        public string Universite { get; set; }

        [StringLength(50, ErrorMessage = "Karakter asimi yaptiniz")]

        public string AnaDal { get; set; }
        [Required(ErrorMessage = "Adres alanı gereklidir.")]

        public string Adres { get; set; }


        [Required(ErrorMessage = "Fakülte alanı gereklidir.")]
        [StringLength(50, ErrorMessage = "Karakter asimi yaptiniz")]
        public string Fakulte { get; set; }


        [Required(ErrorMessage = "Bölüm alanı gereklidir.")]
        [StringLength(50, ErrorMessage = "Karakter asimi yaptiniz")]

        public string Bolum { get; set; }


        public int Id { get; set; }

        public int FKKisiId { get; set; }

        [Required(ErrorMessage = "Lütfen sunum yapmak istediğiniz kongreyi seçin")]
        public int? FKKongreId { get; set; }

        public bool? Onay { get; set; }

        public DateTime? OnayZaman { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        public DateTime BasvuruZaman { get; set; }

        public string BasvuruKodu { get; set; }


        public int? SunumTipi { get; set; }


        [Required(ErrorMessage = "Başlık alanı gereklidir.")]
        public string Baslik { get; set; }


        public string Ozet { get; set; }


        [Required(ErrorMessage = "Lütfen seçim yapınız.")]
        public bool? PosterMi { get; set; }



        public int EvrakId { get; set; }
        public int FKBasvuruId { get; set; }

        public string DosyaTuru { get; set; }

        [Required(ErrorMessage = "Dosya alanı gereklidir.")]
        public string Dosya { get; set; }

        public DateTime Zaman { get; set; }



        [StringLength(50)]
        public string DosyaAdi { get; set; }

        public string KongreAd { get; set; }


        [Required(ErrorMessage = "Oturum")]

        public List<OturumVM> OturumList { get; set; }

        public List<BasvuruDetayVM> DetayList { get; set; }
    }

   
}

KongreForm/Controllers/BasvuruController.cs
using KongreForm.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace KongreForm.Controllers
{
    public class BasvuruController : Controller
    {
        KongreDbEntities db = new KongreDbEntities();

        public ActionResult Index()
        {
            if (Convert.ToBoolean(Session["yetki"]))
            {
                List<Basvuru> basvurulist = db.Basvurus.OrderByDescending(x => x.BasvuruZaman).ToList();
                List<BasvuruViewModel> kongreVMList = basvurulist.Select(x => new BasvuruViewModel

                {
                    Id = x.Id,
                    BasvuruKodu = x.BasvuruKodu,
                    BasvuruZaman = x.BasvuruZaman,
                    SunumTipi = x.SunumTipi,
                    FKKisiId = x.Kisi.Id,
                    FKKongreId = x.Kongre.Id,
                    KongreAd = x.Kongre.KongreAd,
                    Onay = x.Onay,
                    OnayZaman = x.OnayZaman,
                    Ad = x.Kisi.Ad,
                    Soyad = x.Kisi.Soyad,
                    Egitim = x.Kisi.Egitim,
                    Meslek = x.Kisi.Meslek,
                    Universite = x.Kisi.Universite,
                    AnaDal = x.Kisi.AnaDal,
                    Adres = x.Kisi.Adres,
                    Fakulte = x.Kisi.Fakulte,
                    Bolum = x.Kisi.Bolum,
                    Baslik = x.Baslik,
                    PosterMi = x.PosterMi


                }).ToList();
                return View(kongreVMList);
            }
            else
            {
                var kullanici = Convert.ToInt32(Session["kullaniciid"]);
                Yetki yetki = new Yetki();
                yetki.FKKullaniciId = kullanici;

                List<Basvuru> basvurulist = new List<Basvuru>();

                var kongre = db.Yetkis.Where(x => x.FKKullaniciId == kullanici).Select(x => x.FKKongreId).ToList();
                foreach (var item in kongre)
                {
                    var a= db.Basvurus.Where(x => x.FKKongreId == item).OrderByDescending(x => x.BasvuruZaman).ToList();
                    foreach (var item2 in a)
                    {
                        basvurulist.Add(item2);
                    }
                }
                List<BasvuruViewModel> kongreVMList = basvurulist.Select(x => new BasvuruViewModel

                {
                    Id = x.Id,
                    BasvuruKodu = x.BasvuruKodu,
                    BasvuruZaman = x.BasvuruZaman,
                    SunumTipi = x.SunumTipi,
                    FKKisiId = x.Kisi.Id,
                    FKKongreId = x.Kongre.Id,
                    KongreAd = x.Kongre.KongreAd,
                    Onay = x.Onay,
                    OnayZaman = x.OnayZaman,
                    Ad = x.Kisi.Ad,
                    Soyad = x.Kisi.Soyad,
                    Egitim = x.Kisi.Egitim,
                    Meslek = x.Kisi.Meslek,
                    Universite = x.Kisi.Universite,
                    AnaDal = x.Kisi.AnaDal,
                    Adres = x.Kisi.Adres,
                    Fakulte = x.Kisi.Fakulte,
                    Bolum = x.Kisi.Bolum,
                    Baslik = x.Baslik,
                    PosterMi = x.PosterMi



                }).ToList();

                return View(kongreVMList);
            }
        }



        public ActionResult Details(int? id)
        {
            try
            {

                if (id == null)
                {
                    throw new Exception();
                }

                Basvuru b = db.Basvurus.SingleOrDefault(x => x.Id == id);

                if (b == null)
                {
                    throw new Exception();
                }

                BasvuruViewModel kongreVM = new BasvuruViewModel();

                kongreVM.Id = b.Id;
                kongreVM.Ad = b.Kisi.Ad;
                kongreVM.Soyad = b.Kisi.Soyad;
                kongreVM.Meslek = b.Kisi.Meslek;
                kongreVM.Kurum = b.Kisi.Kurum;
                kongreVM.TcNo = b.Kisi.TcNo;
                kongreVM.Telefon = b.Kisi.Telefon;
                kongreVM.Egitim = b.Kisi.Egitim;
                kongreVM.Email = b.Kisi.Email;
                kongreVM.BasvuruZaman = b.BasvuruZaman;
                kongreVM.BasvuruKodu = b.BasvuruKodu;
                kongreVM.FKKongreId = b.Kongre.Id;
                kongreVM.KongreAd = b.Kongre.KongreAd;
                kongreVM.SunumTipi = b.SunumTipi;
                kongreVM.Universite = b.Kisi.Universite;
                kongreVM.AnaDal = b.Kisi.AnaDal;
                kongreVM.Fakulte = b.Kisi.Fakulte;
                kongreVM.Bolum = b.Kisi.Bolum;
                kongreVM.Baslik = b.Baslik;
                kongreVM.Ozet = b.Ozet;
                kongreVM.PosterMi = b.PosterMi;
                kongreVM.Adres = b.Kisi.Adres;

                int SonBasvuruId = b.Id;


                BasvuruEvrak be2 = db.BasvuruEvraks.SingleOrDefault(x => x.FKBasvuruId == b.Id);

                kongreVM.DosyaTuru = be2.DosyaTuru;
                kongreVM.Dosya = be2.Dosya;
                kongreVM.Zaman = be2.Zaman;
                kongreVM.DosyaAdi = be2.DosyaAdi;


                List<BasvuruDetay> bdetay = new List<BasvuruDetay>();

                bdetay = db.BasvuruDetays.Where(x => x.FKBasvuruId == b.Id).ToList();

                kongreVM.DetayList = bdetay.Select(y => new BasvuruDetayVM()
                {
                    FKBasvuruId = y.FKBasvuruId,
                    FKKullaniciId = y.FKKullaniciId,
                    FKOturumId = y.FKOturumId,
                    Id = y.Id,
                    Onay = y.Onay,
                    OnayZaman = y.OnayZaman,
                    OturumAd = y.Oturum.OturumAd
                }).ToList();


                return View(kongreVM);
            }

            catch (Exception)
            {
                return RedirectToAction("Error", "Home");
            }

        }

        public ActionResult Onayla(string submitButton, BasvuruViewModel model)
        {

            string[] tokens = submitButton.Split(',');

            var state = tokens[1];

            var button = tokens[0];



            int buttonnum = Int32.Parse(button);

            BasvuruDetay bdetay = new BasvuruDetay();

            var bdetayid = model.DetayList[buttonnum].Id;
            bdetay = db.BasvuruDetays.Where(x => x.Id == bdetayid).FirstOrDefault();

            if (bdetay != null)
            {
                bdetay.Onay = state == "o";
                bdetay.OnayZaman = DateTime.Now;
                bdetay.FKKullaniciId = Convert.ToInt32(Session["kullaniciid"]);
                db.Entry(bdetay).State = EntityState.Modified;
                db.SaveChanges();
            }


            var bdetaylist = db.BasvuruDetays.Where(x => x.Id == bdetayid).Select(x => x.Onay).ToList();
            var basvuru = db.Basvurus.Where(x => x.Id == model.Id).FirstOrDefault();


            if (bdetaylist.All(x => x == false))
            {
                basvuru.Onay = false;
            }
            else if (bdetaylist.All(x => x == null))
            {
                basvuru.Onay = null;
            }
            else if (bdetaylist.Any(x => x == true))
            {
                basvuru.Onay = true;
            }

            db.Entry(basvuru).State = EntityState.Modified;
            db.SaveChanges();


            return RedirectToAction("Details", new { model.Id });


        }
        [HttpGet]
        [Route("basvurusonuc")]
        public ActionResult Sonuc(int? id)
        {
            KongreDbEntities db = new KongreDbEntities();

            BasvuruViewModel model = new BasvuruViewModel();

            var bdetay = db.BasvuruDetays.Where(x => x.FKBasvuruId == id).Select(y => new BasvuruDetayVM()
            {
                FKBasvuruId = y.FKBasvuruId,
                FKKullaniciId = y.FKKullaniciId,
                FKOturumId = y.FKOturumId,
                Id = y.Id,
                Onay = y.Onay,
                OnayZaman = y.OnayZaman,
                KullaniciAd = y.Kullanici.Ad,
                KullaniciSoyad = y.Kullanici.Soyad,
                OturumAd = y.Oturum.OturumAd


            }).ToList();

            model.DetayList = bdetay;

            try
            {

                if (id == null)
                {
                    throw new Exception();
                }
                Basvuru basvuru = db.Basvurus.Find(id);
                if (basvuru == null)
                {
                    throw new Exception();
                }
                return View(model);
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home");
            }

        }
        public ActionResult Edit(int? id)
        {

            try
            {
                if (id == null)
                {
                    throw new Exception();
                }
                Basvuru basvuru = db.Basvurus.Find(id);

                BasvuruAndEvrakModel model = new BasvuruAndEvrakModel();

                var kisi = db.Basvurus.Where(x => x.Id == basvuru.Id).Select(x => x.FKKisiId).FirstOrDefault();
                var ad = db.Kisis.Where(x => x.Id == kisi).Select(x => x.Ad).FirstOrDefault();
                var soyad = db.Kisis.Where(x => x.Id == kisi).Select(x => x.Soyad).FirstOrDefault();
                var kongre = db.Basvurus.Where(x => x.Id == basvuru.Id).Select(x => x.FKKongreId).FirstOrDefault();
                var kongreAd = db.Kongres.Where(x => x.Id == kongre).Select(x => x.KongreAd).FirstOrDefault();

                model.Baslik = basvuru.Baslik;
                model.PosterMi = basvuru.PosterMi;
                model.Id = basvuru.Id;
                model.Ad = ad;
                model.Soyad = soyad;
                model.KongreAd = kongreAd;
                       

KongreForm/Views/Basvuru/Details.cshtml
@model KongreForm.Models.BasvuruViewModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Basvuru Detay</h2>


<div id="profile" class="tab-pane active">
    <section class="panel">

        <div class="panel-body bio-graph-info">
            <div class="row">
                <div class="bio-row">
                    <p>
                        <span>Basvuru Kodu </span>:@Html.DisplayFor(model => model.BasvuruKodu)
                    </p>
                </div>
                <div class="bio-row">
                    <p><span>Basvurulan Kongre </span>: @Html.DisplayFor(model => model.KongreAd)</p>
                </div>
                <div class="bio-row">
                    <p><span>Basvuru Zaman</span>:  @Html.DisplayFor(model => model.BasvuruZaman)</p>
                </div>
                <div class="bio-row">
                    <p><span>Ad </span>: @Html.DisplayFor(model => model.Ad)</p>
                </div>
                <div class="bio-row">
                    <p><span>Soyad </span>:@Html.DisplayFor(model => model.Soyad)</p>
                </div>
                <div class="bio-row">
                    <p><span>Email </span>: @Html.DisplayFor(model => model.Email)</p>
                </div>
                <div class="bio-row">
                    <p><span>Telefon </span>: @Html.DisplayFor(model => model.Telefon)</p>
                </div>
                <div class="bio-row">
                    <p><span>Üniversite </span>: @Html.DisplayFor(model => model.Universite)</p>
                </div>
                <div class="bio-row">
                    <p><span>Ana Dal </span>: @Html.DisplayFor(model => model.AnaDal)</p>
                </div>
                <div class="bio-row">
                    <p><span>Adres </span>: @Html.DisplayFor(model => model.Adres)</p>
                </div>
                <div class="bio-row">
                    <p><span>Fakülte </span>: @Html.DisplayFor(model => model.Fakulte)</p>
                </div>
                <div class="bio-row">
                    <p><span>Bölüm </span>: @Html.DisplayFor(model => model.Bolum)</p>
                </div>
                <div class="bio-row">
                    <p><span> Başlık</span>: @Html.DisplayFor(model => model.Baslik)</p>
                </div>
                
         

                <div class="bio-row">
                    <p>
                        <span>Dosya URL </span>: @Html.DisplayFor(model => model.DosyaAdi)
                        <a href="~/Home/DownloadFile?filePath=@Model.Id">
                            <img src="~/Images/download.png" style="width: 15px; height: 15px" title="Download" />
                        </a>
                    </p>
                    @{
                        if (ViewBag.Error != null)
                        {
                            <p class="text-danger">@ViewBag.Error</p>
                        }
                    }
                </div>
            </div>
        </div>
    </section>

    <script type="text/javascript">
        function DownloadFile(fileId) {
            $("#hfFileId").val(fileId);
            $("#btnDownload")[0].click();
        };
    </script>


    <h3>Basvurulan Oturumlar</h3>



    @using(Html.BeginForm("Onayla","Basvuru"))
    { 
        <table>
            @for (int i = 0; i < Model.DetayList.Count; i++)
            {
                <tr>
                    <td>
                        @Model.DetayList[i].OturumAd
                        @Html.HiddenFor(model => model.DetayList[i].Id)
                        @Html.HiddenFor(model=>model.DetayList[i].Id)
                        @Html.HiddenFor(model => model.Id)
                    </td>
                    <td>
                        @if (Model.DetayList[i].Onay == true)
                        {
                            <button type = "submit" class="btn btn-success"    name="submitButton" value="@i,0"><i class="fa fa-check"></i>Onaylandı</button>
                            <button type = "submit" class="btn btn-notdanger"  style="width:100px" name="submitButton" value="@i,r"><i class="fa fa-close"></i>Reddet</button>

                        }
                        else if (Model.DetayList[i].Onay == false)
                        {
                            <button type = "submit" class="btn btn-notsuccess"  style="width:100px" name="submitButton" value="@i,o"><i class="fa fa-check"></i>Onayla</button>
                            <button type = "submit" class="btn btn-danger" name="submitButton" value="@i,r"><i class="fa fa-close"></i>Reddedildi</button>

                        }
                        else
                        {
                            <button type = "submit" class="btn btn-notsuccess" style="width:100px" name="submitButton" value="@i,o"><i class="fa fa-check"></i>Onayla</button>
                            <button type = "submit" class="btn btn-notdanger" style="width: 100px" name="submitButton" value="@i,r"><i class="fa fa-close"></i>Reddet</button>
                        }
                    </td>
                </tr>
            }
        </table>
    }
    

    <script>
        function yourJavascriptBeginMethod(value) {

            var buttonValue = getParameterByName(value[0].data, "submitButton");

            switch (buttonValue) {
                case 'Onayla':
                    break;
                case 'Reddet':
                    break;
                default:
            }

        }
        function getParameterByName(data, name) {

            name = name.replace(/[\[]/, "\\[").replace(/[\]]/, "\\]");

            name = '?' + name; 

            var regex = new RegExp("[\\?&]" + name + "=([^&#]*)"), results = regex.exec(data);

            return results === null ? "" : decodeURIComponent(results[1].replace(/\+/g, " "));
        }
    </script>

    <section>
        <div class="row">
        </div>
    </section>
</div>

KongreForm/Views/Basvuru/Edit.cshtml
@model KongreForm.Models.BasvuruAndEvrakModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Basvuru Detayları Guncelle</h2>

@using (Html.BeginForm("Edit", "Basvuru", FormMethod.Post, new { enctype = "multipart/Form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Ad, "Basvuran Kisi Adı", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model =>model.Ad, new {htmlAttributes= new { @class = "form-control" , disabled = "disabled" } })
            @Html.ValidationMessageFor(model => model.Ad, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Soyad, "Basvuran Kisi Soyadı", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Soyad, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
            @Html.ValidationMessageFor(model => model.Soyad, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.KongreAd, "Basvurulan Kongre", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.KongreAd, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
            @Html.ValidationMessageFor(model => model.KongreAd, "", new { @class = "text-danger" })
        </div>
    </div>


    @*<div class="form-group">
            @Html.LabelFor(model => model.PosterMi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.PosterMi)
                    @Html.ValidationMessageFor(model => model.PosterMi, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>*@

    <div class="form-group">
        <span class="control-label col-lg-2">Poster mi?</span>
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.PosterMi, new List<SelectListItem> {
     new SelectListItem{ Value = true.ToString(), Text = "Evet" },
     new SelectListItem{ Value = false.ToString(), Text = "Hayır" },
   }, "Lütfen seçim yapınız", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.PosterMi, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.Baslik, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Baslik, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Baslik, "", new { @class = "text-danger" })
        </div>
    </div>

    <div div class="form-group">
        @Html.LabelFor(model => model.Dosya, htmlAttributes: new { @class = "control-label col-md-2" })

        <br />
        <div class="col-md-10">
            <span style="text-decoration: underline; ">Yüklü Dosya</span>: @Html.DisplayFor(model => model.DosyaAdi)
            <a href="~/Home/DownloadFile?filePath=@Model.Id">
                <img src="~/Images/download.png" style="width: 15px; height: 15px" title="Download" />
            </a>
            @Html.TextBox("Dosya", "", new { type = "file", name = "Dosya" }) <br />



            @Html.ValidationMessageFor(model => model.Dosya, "", new { @class = "text-danger" })
            @{
                if (ViewBag.Message != null)
                {
                    <span class="text-danger"> @ViewBag.Message</span>
                }
            }
        </div>


    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Guncelle" class="btn btn-default" />
        </div>
    </div>
</div>
}

KongreForm/Views/Basvuru/Index.cshtml
@model IEnumerable<KongreForm.Models.BasvuruViewModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<h2>Basvuru Listesi</h2>

<div class="row">
    <div class="col-lg-12">
        <section class="panel">

            <table class="table table-striped table-advance table-hover">
                <tbody>
                    <tr>
                        <th>
                            Ad
                        </th>
                        <th>
                            Soyad
                        </th>
                        <th>
                            Başvurulan Kongre
                        </th>
                        <th>
                            Başvuru Kodu
                        </th>

                        <th>
                            Başvurulan Zaman
                        </th>

                        <th> Üniversite </th>
                       
                        <th> Fakülte</th>
                        <th>Bölüm</th>
                        @*<th>
                            Meslek
                        </th>
                        <th> Eğitim Durumu</th>
                        <th>
                            Katılım Tipi
                        </th>*@
                        <th>
                            Basvuru Durumu
                        </th>
                        <th></th>
                        <th></th>
                    </tr>

                    @foreach (var item in Model)

                    {
                <tr>
                    <td> @item.Ad</td>
                    <td>@item.Soyad</td>
                    <td>@item.KongreAd</td>
                    <td>@item.BasvuruKodu</td>
                    <td>@item.BasvuruZaman.ToShortDateString() - @item.BasvuruZaman.ToShortTimeString()</td>
                    <td>@item.Universite </td>
                    <td>@item.Fakulte</td>
                    <td>@item.Bolum</td>
                    @*<td>  @item.Meslek </td>

        @switch (@item.Egitim)
        {
            case 1:
                <td>İlköğretim</td>
                break;
            case 2:
                <td>Orta Öğretim</td>
                break;
            case 3:
                <td>Lise</td>
                break;
            case 4:
                <td>Meslek Yüksek Okulu</td>
                break;
            case 5:
                <td>Üniversite</td>
                break;
            case 6:
                <td>Yüksek Lisans</td>
                break;
            case 7:
                <td>Doktora</td>
                break;

            default:
                <td></td>
                break;
        }


        @switch (@item.SunucuMu)
        {
            case true:
                <td>Sunucu</td>
                break;
            case false:
                <td>İzleyici</td>
                break;
            default:
                <td></td>
                break;
        }*@


                    <td>
                        @if (@item.Onay.HasValue)
                        {
                            if (item.Onay == true)
                            {

                                <input type="button" style="width: 90px" class="btn btn-success" value="Onaylandı">
                            }

                            else

                            {
                                <input type="button" style="width: 90px" class="btn btn-danger" value="Reddedildi">
                            }

                        }

                        else
                        {
                            <input type="button" style="width: 90px" class="btn btn-default" value="Belirsiz  ">
                        }

                    </td>
                    <td>
                        <a href="/Basvuru/Details?id=@item.Id"> Detay</a>

                    </td>
                    <td>
                        <div class="btn-group">
                            <a href="/Basvuru/Edit?id=@item.Id"> Düzenle</a>
                        </div>
                    </td>
                </tr>

                    }

                </tbody>
            </table>
        </section>
    </div>
</div>