KongreForm/Models/Kongre.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KongreForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kongre
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kongre()
        {
            this.Basvurus = new HashSet<Basvuru>();
            this.Oturums = new HashSet<Oturum>();
            this.Yetkis = new HashSet<Yetki>();
            this.Aktifs = new HashSet<Aktif>();
        }
    
        public int Id { get; set; }
        public string KongreAd { get; set; }
        public System.DateTime Baslangic { get; set; }
        public System.DateTime Bitis { get; set; }
        public Nullable<bool> AktifMi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Basvuru> Basvurus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oturum> Oturums { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yetki> Yetkis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aktif> Aktifs { get; set; }
    }
}

KongreForm/Models/KongreViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace KongreForm.Models
{
    public class KongreViewModel
    {
        public List<KongreModel> KongreList { get;set; }
        public int SelectedKongre { get; set; }
        public List<OturumModel> OturumList { get; set; }
    }

    public class KongreModel
    {
        [Required]
        public string KongreAd { get; set; }

        public DateTime Baslangic { get; set; }

        public DateTime Bitis { get; set; }

        public bool? AdAktifMi { get; set; }


    }

    public class OturumModel
    {
        public int Id { get; set; }

        public int FKKongreId { get; set; }


        [StringLength(150)]
        public string OturumAd { get; set; }

        public DateTime OturumBaslangic { get; set; }

        public DateTime OturumBitis { get; set; }


    }







}

KongreForm/Models/Oturum.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KongreForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oturum
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Oturum()
        {
            this.BasvuruDetays = new HashSet<BasvuruDetay>();
        }
    
        public int Id { get; set; }
        public int FKKongreId { get; set; }
        public string OturumAd { get; set; }
        public System.DateTime OturumBaslangic { get; set; }
        public System.DateTime OturumBitis { get; set; }
        public bool IsChecked { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasvuruDetay> BasvuruDetays { get; set; }
        public virtual Kongre Kongre { get; set; }
    }
}

KongreForm/Controllers/KongreController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KongreForm.Models;

namespace KongreForm.Controllers
{
    public class KongreController : Controller
    {
        private KongreDbEntities db = new KongreDbEntities();

        
        public ActionResult Index()
        {
            if (Convert.ToBoolean(Session["yetki"]))
            {
                return View(db.Kongres.ToList());
            }
            else
            {
                var kullanici = Convert.ToInt32(Session["kullaniciid"]);
                Yetki yetki = new Yetki();
                yetki.FKKullaniciId = kullanici;

                List<Kongre> yetkitumkongre = new List<Kongre>();

                var kongrelist = db.Yetkis.Where(x => x.FKKullaniciId == kullanici).Select(x => x.FKKongreId).ToList();

                foreach (var item in kongrelist)
                {
                    List<Kongre> kongrelist3 = db.Kongres.Where(x => x.Id == item).OrderByDescending(x => x.Id).ToList();
                    foreach (var items in kongrelist3)
                    {
                        yetkitumkongre.Add(items);
                    }

                }


                return View(yetkitumkongre);
            }
               
        }

        public ActionResult Create()
        {
            if (!Convert.ToBoolean(Session["yetki"])) { return RedirectToAction("Index"); }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,KongreAd,Baslangic,Bitis,AktifMi")] Kongre kongre)
        {
            if (!Convert.ToBoolean(Session["yetki"])) { return RedirectToAction("Index"); }

            if (ModelState.IsValid)
            {
                int sayac = 0;
                var nameexists = db.Oturums.Where(x => x.FKKongreId == kongre.Id).Select(x => x.OturumAd).ToList();

                if (nameexists.Any(x => x == kongre.KongreAd))
                {
                    ModelState.AddModelError("KongreAd", "Bu kongre ismiyle oluşturulmuş kongre bulunmaktadır.");
                    sayac++;
                }


                if (kongre.Baslangic < DateTime.Now)
                {
                    ModelState.AddModelError("Baslangic", "Geçmiş bir tarih girdiniz.");
                    sayac++;
                }
                if (kongre.Bitis < DateTime.Now)
                {
                    ModelState.AddModelError("Bitis", "Geçmiş bir tarih girdiniz.");
                    sayac++;
                }

                int result = DateTime.Compare(kongre.Baslangic, kongre.Bitis);
                if (result > 0 || result == 0)
                {
                    ModelState.AddModelError("Bitis", "Bitiş  başlangıçtan önce olamaz.");
                    sayac++;
                }
                if (sayac>0)
                {
                    return View();
                }
                else if (sayac==0)
                {
                    db.Kongres.Add(kongre);
                    db.SaveChanges();
                    return RedirectToAction("Create", "Oturum");
                }
              
            }

            return View(kongre);
        }



        public ActionResult Edit(int? id)
        {
            try
            {
                if (id == null)
                {
                    throw new Exception();
                }
                Kongre kongre = db.Kongres.Find(id);
                if (kongre == null)
                {
                    throw new Exception();
                }
                return View(kongre);
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home");
            }
           
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,KongreAd,Baslangic,Bitis,AktifMi")] Kongre kongre)
        {
            if (ModelState.IsValid)
            {
                int sayac = 0;
                var nameexists = db.Oturums.Where(x => x.FKKongreId == kongre.Id).Select(x => x.OturumAd).ToList();

                if (nameexists.Any(x => x == kongre.KongreAd))
                {
                    ModelState.AddModelError("KongreAd", "Bu kongre ismiyle oluşturulmuş kongre bulunmaktadır.");
                    sayac++;
                }


                if (kongre.Baslangic < DateTime.Now)
                {
                    ModelState.AddModelError("Baslangic", "Geçmiş bir tarih girdiniz.");
                    sayac++;
                }
                if (kongre.Bitis < DateTime.Now)
                {
                    ModelState.AddModelError("Bitis", "Geçmiş bir tarih girdiniz.");
                    sayac++;
                }

                int result = DateTime.Compare(kongre.Baslangic, kongre.Bitis);
                if (result > 0 || result == 0)
                {
                    ModelState.AddModelError("Bitis", "Bitiş  başlangıçtan önce olamaz.");
                    sayac++;
                }
                if (sayac > 0)
                {
                    return View();
                }
                else if (sayac == 0)
                {
                    db.Entry(kongre).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }


            }
            return View(kongre);
        }

       
        public ActionResult Delete(int? id)
        {
            try
            {
                if (id == null)
                {
                    throw new Exception();
                }
                Kongre kongre = db.Kongres.Find(id);
                if (kongre == null)
                {
                    throw new Exception();
                }
                return View(kongre);
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home");
            }
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var basvuru = db.Basvurus.Where(x => x.FKKongreId == id).ToList();
            var oturum = db.Oturums.Where(x => x.FKKongreId == id).ToList();
            var yetki = db.Yetkis.Where(x => x.FKKongreId == id).ToList();
            var aktifmi = db.Aktifs.Where(x => x.FKKongreId == id).ToList();
            var kongre2 = db.Kongres.Where(x => x.Id == id).FirstOrDefault();
            List<string> mesajlist = new List<string>();
            mesajlist.Add("Bu kongre silinemez! ");

            if (basvuru.Count > 0)
            {
                mesajlist.Add("Kongreye kayıtlı başvuru bulunmaktadır.");
                
            }
            if (oturum.Count > 0)
            {
                mesajlist.Add("Kongreye kayıtlı oturum bulunmaktadır.");
                
            }
             if (yetki.Count > 0)
            {
                mesajlist.Add("Kongreye kayıtlı yetki bulunmaktadır.");
                
            }
             if (aktifmi.Count > 0)
            {
                mesajlist.Add("Kongreye kayıtlı aktiflik bulunmaktadır.");
            }

            ViewBag.KongreError = String.Join(" ", mesajlist);
            if (aktifmi.Count == 0 && yetki.Count == 0 && oturum.Count == 0 && basvuru.Count == 0)
            {
                Kongre kongre = db.Kongres.Find(id);
                db.Kongres.Remove(kongre);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return View(kongre2);
            }
           

        }

        public PartialViewResult KongreWidget()
        {
            return PartialView(db.Kongres.ToList());
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


    }
}

KongreForm/Views/Kongre/Create.cshtml
@model KongreForm.Models.Kongre
@*@{int index = Model.Oturumss.Count;}*@
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Yeni kongre olustur</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.KongreAd, "Kongre Adı", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-sm-2">
            @Html.EditorFor(model => model.KongreAd, new { htmlAttributes = new { @class = "form-control " } })<br />

            @Html.ValidationMessageFor(model => model.KongreAd, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Baslangic, "Baslangıc Zamanı", htmlAttributes: new { @class = "control-label col-md-2 " })
        <div class="col-sm-3">
            <div class="input-group date" data-provide="datetimepicker">


                @Html.TextBoxFor(model => model.Baslangic, "{0:yyyy-MM-ddTHH:mm:ss}", new
           {
               @class = "form-control",
               required = "required",
               @type = "datetime-local",
               @value = DateTime.Now.ToString()
           })<br />


                @Html.ValidationMessageFor(model => model.Baslangic, "", new { @class = "text-danger" })

            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Bitis, htmlAttributes: new { @class = "control-label col-md-2 " })
        <div class="col-sm-4">
            <div class="input-group date" id="datetimepicker">
                @Html.TextBoxFor(model => model.Bitis, "{0:yyyy-MM-ddTHH:mm:ss}", new
           {
               @class = "form-control",
               required = "required",
               @type = "datetime-local",
               @value = DateTime.Now.ToString()
           })
                <br />
                @Html.ValidationMessageFor(model => model.Bitis, "", new { @class = "text-danger" })

            </div>
        </div>
    </div>

    <div class="form-group">
        <span class="control-label col-md-2">Kongre Aktif mi?</span>
        <div class="col-sm-2">
            @Html.DropDownListFor(model => model.AktifMi, new List<SelectListItem> {
     new SelectListItem{ Value = true.ToString(), Text = "Evet" },
     new SelectListItem{ Value = false.ToString(), Text = "Hayır" },
   }, "Lütfen seçim yapınız", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.AktifMi, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Olustur" class="btn btn-default" />
        </div>
    </div>
</div>
}

KongreForm/Views/Kongre/Delete.cshtml
@model KongreForm.Models.Kongre

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<h3>Kongreyi silmek istediginize emin misiniz?</h3>
<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            Kongre Adı
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KongreAd)
        </dd>

        <dt>
            Baslangıc Tarihi
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Baslangic)

        </dd>

        <dt>
            Bitis Tarihi
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Bitis)


    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()


        if (ViewBag.KongreError != null)
        {
            <script type="text/javascript">
            
                alert("@ViewBag.KongreError")
            
            </script>
                      
            

        }


        <div class="form-actions no-color">
            <input type="submit" value="Sil" class="btn btn-default" />
        </div>
    }
</div>
@*<script type="text/javascript">

    $(function() {
    // Assign to a javascript variable
    var error = @Html.Raw(Json.Encode(ViewBag.KongreError))
    if (!error) {
        swal(
            error.ErrorTitle,
            error.ErrorMessage,
            'error'
        );
    }
}
</script>*@

KongreForm/Views/Kongre/Edit.cshtml
@model KongreForm.Models.Kongre

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Kongreyi Duzenle</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.KongreAd, "Kongre Adı", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-sm-2">
            @Html.EditorFor(model => model.KongreAd, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.KongreAd, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Baslangic, "Baslangıc Zamanı", htmlAttributes: new { @class = "control-label col-md-2 " })
        <div class="col-sm-3">
            <div class="input-group date" data-provide="datetimepicker">


                @Html.TextBoxFor(model => model.Baslangic, "{0:yyyy-MM-ddTHH:mm:ss}", new
           {
               @class = "form-control",
               required = "required",
               @type = "datetime-local",
               @value = DateTime.Now.ToString()
           })<br />


                @Html.ValidationMessageFor(model => model.Baslangic, "", new { @class = "text-danger" })

            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Bitis, htmlAttributes: new { @class = "control-label col-md-2 " })
        <div class="col-sm-4">
            <div class="input-group date" id="datetimepicker">
                @Html.TextBoxFor(model => model.Bitis, "{0:yyyy-MM-ddTHH:mm:ss}", new
           {
               @class = "form-control",
               required = "required",
               @type = "datetime-local",
               @value = DateTime.Now.ToString()
           })
                <br />
                @Html.ValidationMessageFor(model => model.Bitis, "", new { @class = "text-danger" })

            </div>
        </div>
    </div>


    <div class="form-group">
        <span class="control-label col-md-2">Kongre Aktif mi?</span>
        <div class="col-sm-2">
            @Html.DropDownListFor(model => model.AktifMi, new List<SelectListItem> {
     new SelectListItem{ Value = true.ToString(), Text = "Evet" },
     new SelectListItem{ Value = false.ToString(), Text = "Hayır" },
   }, "Lütfen seçim yapınız", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.AktifMi, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Guncelle" class="btn btn-default" />
        </div>
    </div>
</div>
}

KongreForm/Views/Kongre/Index.cshtml
@model IEnumerable<KongreForm.Models.Kongre>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Kongre Listesi</h2>


<div class="row">
    <div class="col-lg-12">
        <section class="panel">

            <table class="table table-striped table-advance table-hover">
                <tbody>
                    <tr>
                        <th>
                            Kongre Adı
                        </th>
                        <th>
                            Aktif Mi
                        </th>
                        <th>
                            Baslangıc Tarihi
                        </th>
                        <th>
                            Baslangıc Saati
                        </th>
                        <th>
                            Bitis Tarihi
                        </th>
                        <th>
                            Bitis Saati
                        </th>
                        <th></th>
                    </tr>
                    @foreach (var item in Model)
                    {
                <tr>
                    <td>
                        @item.KongreAd
                    </td>
                    
                        @switch (@item.AktifMi)
                        {
                            case true:
                                <td> Aktif</td>
                                break;
                            case false:
                                <td> Aktif Değil</td>
                                break;
                            default:
                                <td>-</td>
                                break;

                        }



                   
                    <td>
                        @item.Baslangic.ToShortDateString()
                    </td>
                    <td>
                        @item.Baslangic.ToShortTimeString()
                    </td>
                    <td>
                        @item.Bitis.ToShortDateString()
                    </td>
                    <td>
                        @item.Bitis.ToShortTimeString()
                    </td>
                    <td>
                        @Html.ActionLink("Düzenle", "Edit", new { id = item.Id }) |
                        @Html.ActionLink("Sil", "Delete", new { id = item.Id })
                    </td>
                </tr>
                    }
                </tbody>
            </table>
        </section>
    </div>
</div>

KongreForm/Views/Kongre/Oturum.cshtml
<!--@model List<KongreForm.Models.Oturum>

@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Kongreye Oturum Ekle</h2>
<style>
    td {
        padding: 5px;
    }
</style>
<div style="width:700px; padding:5px; background-color:white;">
    @using (Html.BeginForm("Oturum", "Kongre", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)


        <hr />
        if (ViewBag.Message != null)
        {
            <div style="border:solid 1px green">
                @ViewBag.Message
            </div>
        }

        <div><a href="#" id="addNew">Yeni Ekle</a></div>
        <table id="dataTable" border="0" cellpadding="0" cellspacing="0">
            <tr>
                <th>Oturum Adı</th>
                <th>Oturum Baslanngıc</th>
                <th>Oturum Bitis</th>
                <th></th>
            </tr>
            @if (Model != null && Model.Count > 0)
            {
                int j = 0;
                foreach (var i in Model)
                {
                    <tr style="border:1px solid black">
                        <td>@Html.TextBoxFor(a => a[j].OturumAd)</td>
                        <td>@Html.TextBoxFor(a => a[j].OturumBaslangic)</td>
                        <td>@Html.TextBoxFor(a => a[j].OturumBitis)</td>
                        <td>
                            @if (j > 0)
                            {
                                <a href="#" class="remove">Kaldır</a>
                            }
                        </td>
                    </tr>
                    j++;
                }
            }-->


            @*@if (Model != null && Model.Oturums.Count > 0)
            {
                int j = 0;
                for (int i = 0; i < Model.Oturums.Count; i++)
                {
                    <tr style="border:1px solid black">
                        <td>@Html.TextBoxFor(m => Model.Oturums[j].OturumAd)</td>
                        <td>@Html.TextBoxFor(m => Model.Oturums[j].OturumBaslangic)</td>
                        <td>@Html.TextBoxFor(m => Model.Oturums[j].OturumBitis)</td>
                        <td>
                            @if (j > 0)
                            {
                                <a href="#" class="remove">Kaldır</a>
                            }
                        </td>
                    </tr>
                    j++;
                }
            }*@
        <!--</table>
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Olustur" class="btn btn-default" />
        </div>
        
    }
</div>
@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
    <script language="javascript">
        $(document).ready(function () {

            //1. Add new row
            $("#addNew").click(function (e) {
                e.preventDefault();
                var $tableBody = $("#dataTable");
                var $trLast = $tableBody.find("tr:last");
                var $trNew = $trLast.clone();

                var suffix = $trNew.find(':input:first').attr('name').match(/\d+/);
                $trNew.find("td:last").html('<a href="#" class="remove">Remove</a>');
                $.each($trNew.find(':input'), function (i, val) {
                    // Replaced Name
                    var oldN = $(this).attr('name');
                    var newN = oldN.replace('[' + suffix + ']', '[' + (parseInt(suffix) + 1) + ']');
                    $(this).attr('name', newN);
                    //Replaced value
                    var type = $(this).attr('type');
                    if (type.toLowerCase() == "text") {
                        $(this).attr('value', '');
                    }

                    // If you have another Type then replace with default value
                    $(this).removeClass("input-validation-error");

                });
                $trLast.after($trNew);

                // Re-assign Validation
                var form = $("form")
                    .removeData("validator")
                    .removeData("unobtrusiveValidation");
                $.validator.unobtrusive.parse(form);
            });

            // 2. Remove
            $('a.remove').live("click", function (e) {
                e.preventDefault();
                $(this).parent().parent().remove();
            });

        });
    </script>
    }-->