KongreForm/Models/Oturum.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KongreForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oturum
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Oturum()
        {
            this.BasvuruDetays = new HashSet<BasvuruDetay>();
        }
    
        public int Id { get; set; }
        public int FKKongreId { get; set; }
        public string OturumAd { get; set; }
        public System.DateTime OturumBaslangic { get; set; }
        public System.DateTime OturumBitis { get; set; }
        public bool IsChecked { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasvuruDetay> BasvuruDetays { get; set; }
        public virtual Kongre Kongre { get; set; }
    }
}

KongreForm/Controllers/OturumController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KongreForm.Models;

namespace KongreForm.Controllers
{
    public class OturumController : Controller
    {
        private KongreDbEntities db = new KongreDbEntities();

        public ActionResult Index()
        {
            if (Convert.ToBoolean(Session["yetki"]))
            {
                var oturums = db.Oturums.Include(o => o.Kongre);
                return View(oturums.ToList());
            }
            else
            {
                var kullanici = Convert.ToInt32(Session["kullaniciid"]);
                Yetki yetki = new Yetki();
                yetki.FKKullaniciId = kullanici;

                var kongrelist = db.Yetkis.Where(x => x.FKKullaniciId == kullanici).Select(x => x.FKKongreId).ToList();
                List<Oturum> olist = new List<Oturum>();
                foreach (var item in kongrelist)
                {
                    var a = db.Oturums.Where(x => x.FKKongreId == item).ToList();
                    foreach (var item2 in a)
                    {
                        olist.Add(item2);
                    }

                }


                return View(olist);
            }
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Oturum oturum = db.Oturums.Find(id);
            if (oturum == null)
            {
                return HttpNotFound();
            }
            return View(oturum);
        }

        public ActionResult Create()
        {
            //Admin etkisindeyse tüm kongrelere oturum ekleme
            if (Convert.ToBoolean(Session["yetki"]))
            {
                ViewBag.FKKongreId = new SelectList(db.Kongres, "Id", "KongreAd");
                return View(/*oturums.ToList()*/);
            }
            //yetkili olduğu kongrelere oturum ekleme
            else
            {

                var kullanici = Convert.ToInt32(Session["kullaniciid"]);
                Yetki yetki = new Yetki();
                yetki.FKKullaniciId = kullanici;

                var kongreIdlist = db.Yetkis.Where(x => x.FKKullaniciId == kullanici).Select(x => x.FKKongreId).ToList();
                List<Kongre> kongreList = new List<Kongre>();
                if (kongreIdlist != null)
                {
                    foreach (var item in kongreIdlist)
                    {
                        var a = db.Kongres.Where(x => x.Id == item).ToList();
                        foreach (var item2 in a)
                        {
                            kongreList.Add(item2);
                        }

                    }
                    ViewBag.FKKongreId = new SelectList(kongreList, "Id", "KongreAd");
                    return View();
                }

            }

            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,FKKongreId,OturumAd,OturumBaslangic,OturumBitis")] Oturum oturum)
        {
            if (ModelState.IsValid)
            {
                var nameexists = db.Oturums.Where(x => x.FKKongreId == oturum.FKKongreId).Select(x => x.OturumAd).ToList();

                int sayac = 0;
                if (nameexists.Any(x => x == oturum.OturumAd))
                {
                    ModelState.AddModelError("OturumAd", "Bu kongre ismiyle oluşturulmuş oturum bulunmaktadır.");
                    sayac++;
                }


                var kongreid = db.Kongres.Where(x => x.Id == oturum.FKKongreId).FirstOrDefault();

                int rbaslangic = DateTime.Compare(kongreid.Baslangic, oturum.OturumBaslangic);
                if (rbaslangic > 0)
                {
                    ModelState.AddModelError("OturumBaslangic", "Oturum baslangıc zamanı kongrenin baslangıc zamanından once olamaz.");
                    sayac++;
                }

                int rbitis = DateTime.Compare(kongreid.Bitis, oturum.OturumBitis);
                if (rbitis < 0)
                {
                    ModelState.AddModelError("OturumBitis", "Oturum bitis zamanı kongrenin bitis zamanından sonra olamaz.");
                    sayac++;
                }
                int result = DateTime.Compare(oturum.OturumBaslangic, oturum.OturumBitis);
                if (result > 0 || result == 0)
                {
                    ModelState.AddModelError("OturumBitis", "Oturun bitişi oturum başlangıcından önce olamaz.");
                    sayac++;
                }
                int result2 = DateTime.Compare(oturum.OturumBaslangic, kongreid.Bitis);
                if (result2 > 0 || result == 0)
                {
                    ModelState.AddModelError("OturumBaslangic", "Oturum başlangıcı kongre bitişinden sonra olamaz.");
                    sayac++;
                }

                if (sayac > 0)
                {
                    ViewBag.FKKongreId = new SelectList(db.Kongres, "Id", "KongreAd", oturum.FKKongreId);

                    return View(oturum);
                }
                else if (sayac == 0)
                {
                    db.Oturums.Add(oturum);
                    db.SaveChanges();
                    TempData["mesaj"] = "Oturum başarıyla oluşturuldu!";
                    ModelState.Clear();

                    return RedirectToAction("Create");
                }

            }

            ViewBag.FKKongreId = new SelectList(db.Kongres, "Id", "KongreAd", oturum.FKKongreId);
            return View(oturum);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Oturum oturum = db.Oturums.Find(id);
            if (oturum == null)
            {
                return HttpNotFound();
            }

            var oturumId = db.Oturums.Where(x => x.Id == id).Select(x => x.FKKongreId).FirstOrDefault();
            var kongrelist = db.Kongres.Where(x => x.Id == oturumId).ToList();


            if (kongrelist != null)
            {
                ViewBag.FKKongreId = new SelectList(kongrelist, "Id", "KongreAd");
            }

            return View(oturum);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FKKongreId,OturumAd,OturumBaslangic,OturumBitis")] Oturum oturum)
        {
            var oturumId = db.Oturums.Where(x => x.Id == oturum.Id).Select(x => x.FKKongreId).FirstOrDefault();
            var kongrelist = db.Kongres.Where(x => x.Id == oturumId).ToList();

            if (ModelState.IsValid)
            {
                int sayac = 0;
                var kongreid = db.Kongres.Where(x => x.Id == oturum.FKKongreId).FirstOrDefault();

                int rbaslangic = DateTime.Compare(kongreid.Baslangic, oturum.OturumBaslangic);
                if (rbaslangic > 0)
                {
                    ModelState.AddModelError("OturumBaslangic", "Oturum başlangıc zamanı kongrenin baslangıc zamanından once olamaz.");
                    sayac++;
                }

                int rbitis = DateTime.Compare(kongreid.Bitis, oturum.OturumBitis);
                if (rbitis < 0)
                {
                    ModelState.AddModelError("OturumBitis", "Oturum bitis zamanı kongrenin bitis zamanından sonra olamaz.");
                    sayac++;
                }
                int result = DateTime.Compare(oturum.OturumBaslangic, oturum.OturumBitis);
                if (result > 0 || result == 0)
                {
                    ModelState.AddModelError("OturumBitis", "Bitiş  başlangıçtan önce olamaz.");
                    sayac++;
                }

                if (sayac > 0)
                {
                    ViewBag.FKKongreId = new SelectList(kongrelist, "Id", "KongreAd", oturum.FKKongreId);
                    return View(oturum);
                }
                else if (sayac == 0)
                {
                    db.Entry(oturum).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

            }
            ViewBag.FKKongreId = new SelectList(kongrelist, "Id", "KongreAd", oturum.FKKongreId);
            return View(oturum);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Oturum oturum = db.Oturums.Find(id);
            if (oturum == null)
            {
                return HttpNotFound();
            }
            return View(oturum);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Oturum oturum = db.Oturums.Find(id);

            var basvuru = db.BasvuruDetays.Where(x => x.FKOturumId == id).ToList();
          
            if (basvuru.Count > 0)
            {
               ViewBag.OturumError = "Bu oturum silinemez. Oturuma kayıtlı başvuru bulunmaktadır.";
                return View(oturum);
                    
            }
            else
            {
                db.Oturums.Remove(oturum);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

           
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

KongreForm/Views/Oturum/Create.cshtml
@model KongreForm.Models.Oturum

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Yeni Oturum Olustur</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FKKongreId, "Kongre Seçin", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-sm-2">
                @Html.DropDownList("FKKongreId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FKKongreId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OturumAd,"Oturum Adı", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-sm-2">
                @Html.EditorFor(model => model.OturumAd, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OturumAd, "", new { @class = "text-danger" })
            
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OturumBaslangic,"Oturum Baslangıc", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-sm-2">
                <div class="input-group date" id="datetimepicker">
                    @Html.TextBoxFor(model => model.OturumBaslangic, "{0:yyyy-MM-ddTHH:mm:ss}", new
               {
                   @class = "form-control",
                   required = "required",
                   @type = "datetime-local",
                   @value = DateTime.Now.ToString()
               })
                    <br />
                    @Html.ValidationMessageFor(model => model.OturumBaslangic, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OturumBitis,"Oturum Bitis", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-sm-2">
                <div class="input-group date" id="datetimepicker">
                    @Html.TextBoxFor(model => model.OturumBitis, "{0:yyyy-MM-ddTHH:mm:ss}", new
               {
                   @class = "form-control",
                   required = "required",
                   @type = "datetime-local",
                   @value = DateTime.Now.ToString()
               })
                    <br />
                    @Html.ValidationMessageFor(model => model.OturumBitis, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Olustur" class="btn btn-default" />
            </div>
        </div>
    </div>

    <section>
        <div class="form-group">
            <dd>
                @if (TempData["mesaj"] != null)
                {
                    <div class="alert alert-success fade in">
                        <button data-dismiss="alert" class="close close-sm" type="button">
                            <i class="icon-remove"></i>
                        </button>
                        <strong>BASARILI!</strong> Oturum başarıyla oluşturuldu.
                    </div>
                }

            </dd>
        </div>
    </section>
    

}



@*@using (Html.BeginForm("Create", "Oturum", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">

            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })


            @if (ViewBag.Message != null)
            {
                <div style="border:solid 1px green">
                    @ViewBag.Message
                </div>
            }

            <div><a href="#" id="addNew">Add New</a></div>
            <table id="dataTable" border="0" cellpadding="0" cellspacing="0">
                <tr>
                    <th>Kongre Seçin</th>
                    <th>Oturum Adı No</th>
                    <th>Oturum Baslangıc</th>
                    <th>Oturum Bitis</th>
                    <th></th>
                </tr>
                @if (Model != null && Model.Count > 0)
                {
                    int j = 0;
                    foreach (var i in Model)
                    {
                        <tr style="border:1px solid black">

                            <td>@Html.DropDownList(a => a[j], "FKKongreId", null, htmlAttributes: new { @class = "form-control" })</td>
                            <td>@Html.TextBoxFor(a => a[j].OturumAd)</td>
                            <td> @Html.TextBoxFor(a => a[j].OturumBaslangic, "{0:yyyy-MM-ddTHH:mm:ss}", new { @class = "form-control", required = "required", @type = "datetime-local", @value = DateTime.Now.ToString() })</td>
                            <td> @Html.TextBoxFor(a => a[j].OturumBitis, "{0:yyyy-MM-ddTHH:mm:ss}", new { @class = "form-control", required = "required", @type = "datetime-local", @value = DateTime.Now.ToString() })</td>
                            <td>
                                @if (j > 0)
                                {
                                    <a href="#" class="remove">Remove</a>
                                }
                            </td>
                        </tr>
                        j++;
                    }
                }
            </table>
            <input type="submit" value="Kaydet" />
            }
        </div>
    }
    @section Scripts{
        @Scripts.Render("~/bundles/jqueryval")
        <script language="javascript">
            $(document).ready(function () {

                //1. Add new row
                $("#addNew").click(function (e) {
                    e.preventDefault();
                    var $tableBody = $("#dataTable");
                    var $trLast = $tableBody.find("tr:last");
                    var $trNew = $trLast.clone();

                    var suffix = $trNew.find(':input:first').attr('name').match(/\d+/);
                    $trNew.find("td:last").html('<a href="#" class="remove">Remove</a>');
                    $.each($trNew.find(':input'), function (i, val) {
                        // Replaced Name
                        var oldN = $(this).attr('name');
                        var newN = oldN.replace('[' + suffix + ']', '[' + (parseInt(suffix) + 1) + ']');
                        $(this).attr('name', newN);
                        //Replaced value
                        var type = $(this).attr('type');
                        if (type.toLowerCase() == "text") {
                            $(this).attr('value', '');
                        }

                        // If you have another Type then replace with default value
                        $(this).removeClass("input-validation-error");

                    });
                    $trLast.after($trNew);

                    // Re-assign Validation
                    var form = $("form")
                        .removeData("validator")
                        .removeData("unobtrusiveValidation");
                    $.validator.unobtrusive.parse(form);
                });

                // 2. Remove
                $('a.remove').live("click", function (e) {
                    e.preventDefault();
                    $(this).parent().parent().remove();
                });

            });
        </script>
    }*@

KongreForm/Views/Oturum/Delete.cshtml
@model KongreForm.Models.Oturum

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}



<h3>Bu oturumu silmek istediginizden emin misiniz?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Kongre.KongreAd)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kongre.KongreAd)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OturumAd)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OturumAd)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OturumBaslangic)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OturumBaslangic)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OturumBitis)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OturumBitis)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Sil" class="btn btn-default" />
        </div>
    }
</div>


@if (ViewBag.OturumError != null)
{

    <script type="text/javascript">
       alert('@ViewBag.OturumError')
    </script>

}

KongreForm/Views/Oturum/Edit.cshtml
@model KongreForm.Models.Oturum

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Oturumu Duzenle</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.FKKongreId, "Kongre Seçin", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-sm-2">
                @Html.DropDownList("FKKongreId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FKKongreId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OturumAd,"Oturum Seçin", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-sm-2">
                @Html.EditorFor(model => model.OturumAd, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OturumAd, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OturumBaslangic, "Oturum Baslangıç", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-sm-2">
                <div class="input-group date" id="datetimepicker">
                    @Html.TextBoxFor(model => model.OturumBaslangic, "{0:yyyy-MM-ddTHH:mm:ss}", new
               {
                   @class = "form-control",
                   required = "required",
                   @type = "datetime-local",
                   @value = DateTime.Now.ToString()
               })
                    <br />
                    @Html.ValidationMessageFor(model => model.OturumBaslangic, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OturumBitis, "Oturum Bitis", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-sm-2">
                <div class="input-group date" id="datetimepicker">
                    @Html.TextBoxFor(model => model.OturumBitis, "{0:yyyy-MM-ddTHH:mm:ss}", new
               {
                   @class = "form-control",
                   required = "required",
                   @type = "datetime-local",
                   @value = DateTime.Now.ToString()
               })
                    <br />
                    @Html.ValidationMessageFor(model => model.OturumBitis, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kaydet" class="btn btn-default" />
            </div>
        </div>
    </div>
}

KongreForm/Views/Oturum/Index.cshtml
@model IEnumerable<KongreForm.Models.Oturum>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Oturumları Listele</h2>

<table class="table">
    <tr>
        <th>
            Kongre Adı
        </th>
        <th>
            Oturum Adı
        </th>
        <th>
            Baslangıc Zamanı
        </th>
        <th>
            Bitis Zamanı      
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Kongre.KongreAd)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OturumAd)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OturumBaslangic)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OturumBitis)
        </td>
        <td>
            @Html.ActionLink("Düzenle", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Sil", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>