KongreForm/Models/Aktif.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KongreForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aktif
    {
        public int Id { get; set; }
        public int FKKongreId { get; set; }
        public int AktifAlanId { get; set; }
    
        public virtual Kongre Kongre { get; set; }
    }
}

KongreForm/Models/AktifViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace KongreForm.Models
{
    public class AktifCheck
    {
        public int Id { get; set; }
        public string Icerik { get; set; }
        public bool IsChecked { get; set; }

    }
    public class AktifViewModel
    {

        public int AktifAlanId { get; set; }
        public int FKKongreId { get; set; }
        public List<AktifCheck> AktifItems { get; set; }


    }
}

KongreForm/Controllers/AktifController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KongreForm.Models;

namespace KongreForm.Controllers
{
    public class AktifController : Controller
    {
        private KongreDbEntities db = new KongreDbEntities();

        // GET: Aktifs
        public ActionResult Index()
        {
            if (!Convert.ToBoolean(Session["yetki"])) { return RedirectToAction("Index"); }
            var aktifs = db.Aktifs.Include(a => a.Kongre);
            return View(aktifs.ToList());
        }

        public PartialViewResult GetAktifAlan(int KongreId)
        {

            var aktiflist = new List<AktifCheck>()
            {
                new AktifCheck(){ Id = 1, Icerik = "Ad" , IsChecked = false },
                new AktifCheck(){ Id = 2, Icerik = "Soyad" , IsChecked = false },
                new AktifCheck(){ Id = 3, Icerik = "Email" , IsChecked = false },
                new AktifCheck(){ Id = 4, Icerik = "TcNo" , IsChecked = false },
                new AktifCheck(){ Id = 5, Icerik = "Kurum" , IsChecked = false },
                new AktifCheck(){ Id = 6, Icerik = "Meslek" , IsChecked = false },
                new AktifCheck(){ Id = 7, Icerik = "Egitim" , IsChecked = false },
                new AktifCheck(){ Id = 8, Icerik = "Telefon" , IsChecked = false },
                new AktifCheck(){ Id = 9, Icerik = "Universite" , IsChecked = false },
                new AktifCheck(){ Id = 10, Icerik = "AnaDal" , IsChecked = false },
                new AktifCheck(){ Id = 11, Icerik = "Adres" , IsChecked = false },
                new AktifCheck(){ Id = 12, Icerik = "Fakulte" , IsChecked = false },
                new AktifCheck(){ Id = 13, Icerik = "Bolum" , IsChecked = false },
                new AktifCheck(){ Id = 14, Icerik = "SunumTipi" , IsChecked = false },
                new AktifCheck(){ Id = 15, Icerik = "SunucuMu" , IsChecked = false },
                new AktifCheck(){ Id = 16, Icerik = "SunumBaslik" , IsChecked = false },
                new AktifCheck(){ Id = 17, Icerik = "BildiriBaslik" , IsChecked = false },
                new AktifCheck(){ Id = 18, Icerik = "PosterBaslik" , IsChecked = false },
                new AktifCheck(){ Id = 19, Icerik = "Ozet" , IsChecked = false },
                new AktifCheck(){ Id = 20, Icerik = "PosterMi" , IsChecked = false },
                new AktifCheck(){ Id = 21, Icerik = "Dosya" , IsChecked = false },


            };

            KongreDbEntities db = new KongreDbEntities();

            BasvuruViewModel model = new BasvuruViewModel();

            model.FKKongreId = KongreId;

            var aktifs = db.Aktifs.Where(x => x.FKKongreId == KongreId).Select(x => x.AktifAlanId).ToList();

            List<string> aktifler = new List<string>();

            foreach (var item in aktiflist)
            {
                
                if (aktifs.Contains(item.Id))
                {
                    aktifler.Add(item.Icerik);
                    
                }
            }
            ViewBag.aktiflist = aktifler;


            return PartialView("_GetAktifAlan", ViewBag.aktiflist);
        }

        // GET: Aktifs/Create
        public ActionResult Create()
        {

            if (!Convert.ToBoolean(Session["yetki"])) { return RedirectToAction("Index"); }
            var aktif = new List<AktifCheck>()
            {
                new AktifCheck(){ Id = 1, Icerik = "Ad" , IsChecked = false },
                new AktifCheck(){ Id = 2, Icerik = "Soyad" , IsChecked = false },
                new AktifCheck(){ Id = 3, Icerik = "Email" , IsChecked = false },
                new AktifCheck(){ Id = 4, Icerik = "TcNo" , IsChecked = false },
                new AktifCheck(){ Id = 5, Icerik = "Kurum" , IsChecked = false },
                new AktifCheck(){ Id = 6, Icerik = "Meslek" , IsChecked = false },
                new AktifCheck(){ Id = 7, Icerik = "Egitim" , IsChecked = false },
                new AktifCheck(){ Id = 8, Icerik = "Telefon" , IsChecked = false },
                new AktifCheck(){ Id = 9, Icerik = "Universite" , IsChecked = false },
                new AktifCheck(){ Id = 10, Icerik = "AnaDal" , IsChecked = false },
                new AktifCheck(){ Id = 11, Icerik = "Adres" , IsChecked = false },
                new AktifCheck(){ Id = 12, Icerik = "Fakulte" , IsChecked = false },
                new AktifCheck(){ Id = 13, Icerik = "Bolum" , IsChecked = false },
                new AktifCheck(){ Id = 14, Icerik = "SunumTipi" , IsChecked = false },
                new AktifCheck(){ Id = 15, Icerik = "SunucuMu" , IsChecked = false },
                new AktifCheck(){ Id = 16, Icerik = "SunumBaslik" , IsChecked = false },
                new AktifCheck(){ Id = 17, Icerik = "BildiriBaslik" , IsChecked = false },
                new AktifCheck(){ Id = 18, Icerik = "PosterBaslik" , IsChecked = false },
                new AktifCheck(){ Id = 19, Icerik = "Ozet" , IsChecked = false },
                new AktifCheck(){ Id = 20, Icerik = "PosterMi" , IsChecked = false },
                new AktifCheck(){ Id = 21, Icerik = "Dosya" , IsChecked = false },


            };

            AktifViewModel model = new AktifViewModel();
            model.AktifItems = aktif;



            ViewBag.FKKongreId = new SelectList(db.Kongres, "Id", "KongreAd");
            return View(model);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(AktifViewModel model)
        {
            if (ModelState.IsValid)
            {


                foreach (var item in model.AktifItems)
                {
                    if (item.IsChecked == true)
                    {
                        Aktif a = new Aktif();
                        a.FKKongreId = model.FKKongreId;
                        a.AktifAlanId = item.Id;
                        db.Aktifs.Add(a);
                        db.SaveChanges();

                    }

                }

                return RedirectToAction("Index");

            }
            ViewBag.FKKongreId = new SelectList(db.Kongres, "Id", "KongreAd", model.FKKongreId);
            return View(model);
        }

       
        public ActionResult Edit(int? id)
        {
            if (!Convert.ToBoolean(Session["yetki"])) { return RedirectToAction("Index"); }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Aktif aktif = db.Aktifs.Find(id);
            if (aktif == null)
            {
                return HttpNotFound();
            }
            ViewBag.FKKongreId = new SelectList(db.Kongres, "Id", "KongreAd", aktif.FKKongreId);
            return View(aktif);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FKKongreId,AktifCheck")] Aktif aktif)
        {
            if (ModelState.IsValid)
            {
                db.Entry(aktif).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.FKKongreId = new SelectList(db.Kongres, "Id", "KongreAd", aktif.FKKongreId);
            return View(aktif);
        }

       

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

KongreForm/Views/Aktif/Create.cshtml
@model KongreForm.Models.AktifViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Aktif Alan Ekle</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.FKKongreId, "Kongre Seçin", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("FKKongreId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.FKKongreId, "", new { @class = "text-danger" })
        </div>
    </div>
    </div>

<div class="form-group" >
    @Html.LabelFor(model => model.AktifAlanId, "Aktif Olacak Alanları Secin", htmlAttributes: new { @class = "control-label col-md-2" })
    <div  id="aktifcheckbox" class="col-md-10" style="margin-top:10px">
        @for (int i = 0; i < Model.AktifItems.Count; i++)
        {
        <table>
            <tr>
                <td>
                    @Html.CheckBoxFor(m => Model.AktifItems[i].IsChecked, new { @class = "checkbox" })
                </td>
                <td>
                    @Model.AktifItems[i].Icerik
                </td>
            </tr>
            @Html.HiddenFor(m => Model.AktifItems[i].Id)
            @Html.HiddenFor(m => Model.AktifItems[i].Icerik)

        </table>
        }
    </div>
    </div>

 

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Ekle" class="btn btn-default"  />
        </div>
    </div>

    
}

<script>



        $(document).ready(function () {
        $('.aktifcheckbox').change(function (event) {
            var list = [];
            $('#checkbox input:checked').each(function () {
                list.push(this.name);
            });

            $.ajax({
            url: '@Url.Action("Create","Aktif")',
            type: 'POST',
            data: { model: list},
            success: function (result) {
                alert("success");
            },
            error: function (result) {
            }
        });
        });
    });

</script>

KongreForm/Views/Aktif/Edit.cshtml
@model KongreForm.Models.Aktif

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Aktif Alan Duzenle</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.FKKongreId, "FKKongreId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("FKKongreId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FKKongreId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AktifAlanId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AktifAlanId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AktifAlanId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Duzenle" class="btn btn-default" />
            </div>
        </div>
    </div>
}

KongreForm/Views/Aktif/Index.cshtml
@model IEnumerable<KongreForm.Models.Aktif>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Kongredeki Aktif Alanlar</h2>


<table class="table">
    <tr>
        <th>
            Aktif Alan 
        </th>
        <th>
            Kongre Adı
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    
<tr>

    @switch (@item.AktifAlanId)
    {
        case 1:
            <td>Ad</td>
            break;
        case 2:
            <td>Soyad</td>
            break;
        case 3:
            <td>Email</td>
            break;
        case 4:
            <td>Tc Kimlik No</td>
            break;
        case 5:
            <td>Calıstıgı Kurum</td>
            break;
        case 6:
            <td>Meslek</td>
            break;
        case 7:
            <td>Egitim</td>
            break;
        case 8:
            <td>Telefon</td>
            break;
        case 9:
            <td>Universite</td>
            break;
        case 10:
            <td>Ana Dal</td>
            break;
        case 11:
            <td>Adres</td>
            break;
        case 12:
            <td>Fakulte</td>
            break;
        case 13:
            <td>Bolum</td>
            break;
        case 14:
            <td>Sunum Tipi</td>
            break;
        case 15:
            <td>Katılım Türü</td>
            break;
        case 16:
            <td>Sunum Baslik</td>
            break;
        case 17:
            <td>Bildiri Baslik</td>
            break;
        case 18:
            <td>Poster Baslik</td>
            break;
        case 19:
            <td>Ozet</td>
            break;
        case 20:
            <td>Poster Mi</td>
            break;
        case 21:
            <td>Dosya</td>
            break;
        default:
            <td></td>
            break;
    }



    <td>
        @Html.DisplayFor(modelItem => item.Kongre.KongreAd)
    </td>
    <td>
        @Html.ActionLink("Düzenle", "Edit", new { id = item.Id })
    </td>
</tr>
}

</table>